export type Lang = "pt" | "en";

export const dict = {
  pt: {
    nav: {
      capacidades: "Capacidades",
      fluxo: "Fluxo",
      casos: "Outliers",
      video: "Vídeo",
      dados: "Dados",
      seguranca: "Segurança",
      privacidade: "Privacidade",
    },
    hero: {
      tag: "skill para canais dark / faceless",
      l1: "Da ideia",
      l2a: "ao",
      l2redact: "arquivo",
      l2b: "que",
      l3: "se paga.",
      lead: "Um cérebro único que funde o algoritmo do YouTube, o guia de produção do MrBeast, os dados de 2026 e os seus canais. Planeja, empacota, roteiriza, produz — e aprende com o resultado.",
      github: "Ver no GitHub →",
      how: "Como funciona",
      scroll: "role para abrir o arquivo",
      floats: ["FILE 01 · 21:00 BRT · LONG", "OUTLIER 48.6× · COLD FILE DIARIES", "NEON · POSTGRES · OK"],
    },
    cap: {
      eyebrow: "Capacidades",
      title: "Um sistema, não um prompt.",
      sub: "Cada peça da operação de um canal dark — do gancho à esteira de produção — destilada, testada e ligada aos seus próprios pipelines.",
      items: [
        ["Algoritmo & retenção", "Shorts (engaged views, swipe-away, loops) e long-form (CTR, AVD, AVP, 1º minuto, por minuto)."],
        ["Roteiro & hooks", "Y1–Y11 de títulos, cold open, promise stack, escalada, rehooks a cada 2–4 min, final abrupto."],
        ["Thumbnails & A/B", "Psicologia de clique, composição legível a 120px, 3 variantes para Test & Compare."],
        ["Monetização", "Trilha 0→YPP, playbook das 4.000h, funil Short→long, produto digital $7–27."],
        ["Auto-evolução", "Puxa métricas reais, detecta outliers e propõe mudanças com evidência. Nada muda sem seu OK."],
        ["Entende o canal", "Lê calendário, regras travadas e a corrente de teaser antes de gerar qualquer coisa."],
      ],
    },
    outliers: {
      eyebrow: "Dados reais",
      title: "O que o algoritmo já respondeu.",
      sub: "Outliers detectados automaticamente no canal Cold File Diaries — vídeos que bateram a própria baseline. O padrão venceu: loop.",
      note: "AVP acima de 100% = o Short foi assistido em loop. É o sinal mais forte que existe.",
      labels: { views: "views", avp: "AVP", subs: "inscritos", median: "mediana" },
      items: [
        { name: "Springfield Three", fmt: "Short", views: 1180, avp: 136.7, subs: 4, tag: "MELHOR — loop" },
        { name: "D.B. Cooper — $200k", fmt: "Short", views: 1190, avp: 67.2, subs: 1, tag: "dinheiro no hook" },
        { name: "Yuba County Five", fmt: "Short", views: 1202, avp: 43.8, subs: 1, tag: "alcance, sem loop" },
      ],
      medianNote: "Longs ficam entre 0–70 views. O conteúdo retém (AVD de 15 min); falta é tráfego.",
    },
    video: {
      eyebrow: "Amostra",
      title: "Um Short real, feito com a skill.",
      sub: "O outlier de melhor desempenho do canal — o que projetou o loop e puxou inscritos.",
      watch: "Abrir no YouTube",
    },
    fluxo: {
      eyebrow: "Fluxo",
      title: "Comandos que operam o canal.",
      sub: "Setar o foco, entender o canal, produzir, auditar e revisar — tudo por comando.",
      cmds: [
        ["/dark-canal", "Lê o projeto: calendário, regras e corrente de teaser."],
        ["/dark", "Ideia → título → thumb → roteiro → checklist."],
        ["/dark-visual", "Visual Bible, cenas, stills e iteração visual Remotion."],
        ["/dark-build", "Roda o pipeline de produção do canal alvo."],
        ["/dark-audit", "Gate anti-inauthentic + YPP + divulgação de IA."],
        ["/dark-scan", "Varre canais e alerta outliers acima da baseline."],
        ["/dark-revisar", "Loop semanal: métricas → aprendizados → propostas."],
        ["/dark-monetizar", "Trilha 0→YPP com metas e checkpoints."],
      ],
      agents: [
        ["strategist", "Ideação, packaging e diagnóstico por métrica."],
        ["roteirista", "Long-form (5 atos) e Shorts (hook + loop)."],
        ["packager", "Títulos, capítulos e plano de A/B."],
        ["artdirector", "Visual Bible, cenas, assets e iteração visual."],
        ["visual-reviewer", "Revisão independente de render, motion e acabamento."],
        ["auditor", "Compliance YPP e conteúdo inautêntico."],
        ["produtor", "Executa imagens, voz e motion por canal."],
        ["analyst", "Lê métricas e propõe evolução com evidência."],
        ["scout", "Nichos, subnichos e outliers de concorrentes."],
      ],
    },
    dados: {
      eyebrow: "Motor de dados",
      title: "Métricas reais, memória que cresce.",
      sub: "Conecta à YouTube Analytics API via OAuth, grava snapshots em Postgres (Neon) e alimenta um loop de melhoria contínua. Sem banco pago, sem chute.",
      stats: ["references", "comandos", "subagentes", "scripts"],
    },
    seg: {
      eyebrow: "Segurança",
      title: "Suas chaves, sua máquina.",
      body1: "As credenciais do Google e a string de banco ficam",
      bodyEm1: "fora do repositório",
      body2: ", numa pasta local de segredos. O token só acessa",
      bodyEm2: "leitura",
      body3: "do seu próprio canal.",
    },
    footer: {
      text: "Skill open-source para planejar, produzir e monetizar canais dark no YouTube. Feita para rodar dentro do opencode, sobre os seus próprios pipelines.",
      github: "GitHub",
      privacy: "Privacidade",
    },
    privacy: {
      title: "Política de Privacidade",
      updated: "Última atualização: 21 de setembro de 2026.",
      intro: 'Esta política descreve como o projeto dark-master ("nós", "a skill") acessa, usa e protege dados ao se conectar à API do YouTube em nome do usuário.',
      sections: [
        ["1. Quais dados acessamos", "Com a sua autorização explícita via login do Google (OAuth 2.0), a skill pode ler, somente do canal que você autorizar: métricas do YouTube Analytics (views, tempo de exibição, retenção, inscritos, receita estimada) e metadados públicos dos vídeos e da conta. Todos os escopos são de leitura (youtube.readonly, yt-analytics.readonly, yt-analytics-monetary.readonly). Não publicamos, editamos ou apagamos nada no seu canal."],
        ["2. Como usamos os dados", "Exclusivamente para análise e melhoria de desempenho do seu próprio canal — identificar outliers, retenção, conversões e oportunidades de conteúdo. Sem publicidade, perfilamento de terceiros ou qualquer fim alheio a essa análise."],
        ["3. Onde os dados ficam armazenados", "As credenciais (client_secrets.json, yt-token.json) e a string de banco (dark.env) ficam na sua máquina, fora do repositório. As métricas são gravadas no seu próprio banco (Postgres/Neon que você configurar) ou localmente (SQLite)."],
        ["4. Compartilhamento", "Não vendemos, alugamos nem compartilhamos seus dados. Não há rastreamento, analytics de terceiros ou anúncios. Exceto por exigência legal, os dados não saem do seu controle."],
        ["5. Retenção e exclusão", "Revogue o acesso a qualquer momento em myaccount.google.com/permissions. Para apagar os dados locais, remova a pasta de segredos e o banco. Tokens em modo Teste do Google expiram automaticamente; reautorize quando quiser."],
        ["6. Segurança", "Menor privilégio (apenas leitura) e credenciais fora de qualquer repositório versionado. Nenhum método é 100% infalível; mantenha suas chaves privadas."],
        ["7. Cookies e hospedagem", "Site estático, sem cookies próprios. A hospedagem (Vercel) e as fontes (Google Fonts) podem registrar dados técnicos conforme suas próprias políticas."],
        ["8. Menores", "Não destinada a menores de 13 anos; não coletamos dados de crianças intencionalmente."],
        ["9. Alterações", "Podemos atualizar esta política. A data no topo indica a última revisão."],
        ["10. Contato", "Dúvidas: warface01031999@gmail.com."],
      ],
    },
  },
  en: {
    nav: {
      capacidades: "Capabilities",
      fluxo: "Workflow",
      casos: "Outliers",
      video: "Video",
      dados: "Data",
      seguranca: "Security",
      privacidade: "Privacy",
    },
    hero: {
      tag: "skill for dark / faceless channels",
      l1: "From idea",
      l2a: "to",
      l2redact: "archive",
      l2b: "that",
      l3: "pays off.",
      lead: "One brain that merges the YouTube algorithm, the MrBeast production guide, 2026 data and your own channels. It plans, packages, scripts, produces — and learns from the result.",
      github: "View on GitHub →",
      how: "How it works",
      scroll: "scroll to open the file",
      floats: ["FILE 01 · 21:00 BRT · LONG", "OUTLIER 48.6× · COLD FILE DIARIES", "NEON · POSTGRES · OK"],
    },
    cap: {
      eyebrow: "Capabilities",
      title: "A system, not a prompt.",
      sub: "Every piece of running a dark channel — from the hook to the production line — distilled, tested and wired to your own pipelines.",
      items: [
        ["Algorithm & retention", "Shorts (engaged views, swipe-away, loops) and long-form (CTR, AVD, AVP, first minute, per-minute)."],
        ["Script & hooks", "Y1–Y11 titles, cold open, promise stack, escalation, rehooks every 2–4 min, abrupt ending."],
        ["Thumbnails & A/B", "Click psychology, composition readable at 120px, 3 variants for Test & Compare."],
        ["Monetization", "0→YPP track, the 4,000-hour playbook, Short→long funnel, $7–27 digital product."],
        ["Self-evolution", "Pulls real metrics, detects outliers and proposes changes with evidence. Nothing changes without your OK."],
        ["Understands the channel", "Reads calendar, locked rules and the teaser chain before generating anything."],
      ],
    },
    outliers: {
      eyebrow: "Real data",
      title: "What the algorithm already answered.",
      sub: "Outliers auto-detected on the Cold File Diaries channel — videos that beat their own baseline. The pattern won: loops.",
      note: "AVP above 100% = the Short was watched on loop. It is the strongest signal there is.",
      labels: { views: "views", avp: "AVP", subs: "subs", median: "median" },
      items: [
        { name: "Springfield Three", fmt: "Short", views: 1180, avp: 136.7, subs: 4, tag: "BEST — loop" },
        { name: "D.B. Cooper — $200k", fmt: "Short", views: 1190, avp: 67.2, subs: 1, tag: "money in the hook" },
        { name: "Yuba County Five", fmt: "Short", views: 1202, avp: 43.8, subs: 1, tag: "reach, no loop" },
      ],
      medianNote: "Longs sit between 0–70 views. The content retains (AVD of 15 min); what's missing is traffic.",
    },
    video: {
      eyebrow: "Sample",
      title: "A real Short, made with the skill.",
      sub: "The channel's best-performing outlier — the one that engineered the loop and pulled subscribers.",
      watch: "Open on YouTube",
    },
    fluxo: {
      eyebrow: "Workflow",
      title: "Commands that run the channel.",
      sub: "Set the focus, understand the channel, produce, audit and review — all by command.",
      cmds: [
        ["/dark-canal", "Reads the project: calendar, rules and teaser chain."],
        ["/dark", "Idea → title → thumb → script → checklist."],
        ["/dark-visual", "Visual Bible, scenes, stills and Remotion iterations."],
        ["/dark-build", "Runs the target channel's production pipeline."],
        ["/dark-audit", "Anti-inauthentic + YPP + AI disclosure gate."],
        ["/dark-scan", "Scans channels and alerts on outliers above baseline."],
        ["/dark-revisar", "Weekly loop: metrics → learnings → proposals."],
        ["/dark-monetizar", "0→YPP track with goals and checkpoints."],
      ],
      agents: [
        ["strategist", "Ideation, packaging and metric diagnosis."],
        ["roteirista", "Long-form (5 acts) and Shorts (hook + loop)."],
        ["packager", "Titles, chapters and A/B plan."],
        ["artdirector", "Visual Bible, scenes, assets and visual iteration."],
        ["visual-reviewer", "Independent render, motion and finishing review."],
        ["auditor", "YPP compliance and inauthentic content."],
        ["produtor", "Runs images, voice and motion per channel."],
        ["analyst", "Reads metrics and proposes evidence-based changes."],
        ["scout", "Niches, sub-niches and competitor outliers."],
      ],
    },
    dados: {
      eyebrow: "Data engine",
      title: "Real metrics, growing memory.",
      sub: "Connects to the YouTube Analytics API via OAuth, stores snapshots in Postgres (Neon) and feeds a continuous improvement loop. No paid DB, no guessing.",
      stats: ["references", "commands", "subagents", "scripts"],
    },
    seg: {
      eyebrow: "Security",
      title: "Your keys, your machine.",
      body1: "Google credentials and the database string stay",
      bodyEm1: "out of the repository",
      body2: ", in a local secrets folder. The token only accesses",
      bodyEm2: "read",
      body3: "of your own channel.",
    },
    footer: {
      text: "Open-source skill to plan, produce and monetize dark channels on YouTube. Built to run inside opencode, on top of your own pipelines.",
      github: "GitHub",
      privacy: "Privacy",
    },
    privacy: {
      title: "Privacy Policy",
      updated: "Last updated: September 21, 2026.",
      intro: 'This policy describes how the dark-master project (the "skill") accesses, uses and protects data when connecting to the YouTube API on the user\'s behalf.',
      sections: [
        ["1. What data we access", "With your explicit authorization via Google login (OAuth 2.0), the skill can read, only from the channel you authorize: YouTube Analytics metrics (views, watch time, retention, subscribers, estimated revenue) and public metadata of videos and account. All scopes are read-only (youtube.readonly, yt-analytics.readonly, yt-analytics-monetary.readonly). We do not publish, edit or delete anything on your channel."],
        ["2. How we use the data", "Exclusively to analyze and improve your own channel's performance — identifying outliers, retention, conversions and content opportunities. No advertising, third-party profiling or any purpose other than this analysis."],
        ["3. Where data is stored", "Credentials (client_secrets.json, yt-token.json) and the database string (dark.env) stay on your machine, outside the repository. Metrics are stored in your own database (the Postgres/Neon you configure) or locally (SQLite)."],
        ["4. Sharing", "We do not sell, rent or share your data. There is no tracking, third-party analytics or ads. Except where required by law, data does not leave your control."],
        ["5. Retention and deletion", "Revoke access anytime at myaccount.google.com/permissions. To delete local data, remove the secrets folder and the database. Tokens in Google's Testing mode expire automatically; reauthorize whenever you want."],
        ["6. Security", "Least privilege (read-only) and credentials outside any versioned repository. No method is 100% foolproof; keep your keys private."],
        ["7. Cookies and hosting", "Static site, no first-party cookies. Hosting (Vercel) and fonts (Google Fonts) may log technical data under their own policies."],
        ["8. Minors", "Not intended for children under 13; we do not knowingly collect data from children."],
        ["9. Changes", "We may update this policy. The date at the top indicates the latest revision."],
        ["10. Contact", "Questions: warface01031999@gmail.com."],
      ],
    },
  },
} satisfies Record<Lang, unknown>;

export type Dict = typeof dict["pt"];
